### ISSUE TITLE
Exercise2 - invoca resultado do ficheiro 1 e não apenas as funções

### ISSUE THREAD

**Issue by RitaRamo** [joeltecnico/Information-Processing-and-Retrieval-Project#1]
No file exercise2.py está a ser chamado o output do ficheiro 1 (proj1.py), quando devia apenas correr as funcoes chamadas e não o ficheiro. Alguem pode resolver isso?

**Comment by joelalmeidaptg** [comment]
Eu vejo logo à tarde. Estou em aulas


Obrigado, Joel Almeida
-------- Original message --------From: Rita Parada Ramos <notifications@github.com> Date: 23/10/2017  12:29  (GMT+00:00) To: joeltecnico/PRI-Project <PRI-Project@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [joeltecnico/PRI-Project] Exercise2 - invoca resultado do ficheiro 1 e não apenas as funções (#1) 
No file exercise2.py está a ser chamado o output do ficheiro 1 (proj1.py), quando devia apenas correr as funcoes chamadas e não o ficheiro. Alguem pode resolver isso?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/joeltecnico/PRI-Project","title":"joeltecnico/PRI-Project","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/joeltecnico/PRI-Project"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Exercise2 - invoca resultado do ficheiro 1 e não apenas as funções (#1)"}],"action":{"name":"View Issue","url":"https://github.com/joeltecnico/PRI-Project/issues/1"}}}
